@host = localhost:5001
@contentType = application/json

### Get Status
# @name getStatus
GET http://{{host}}/extract?id=c1f35e45-8148-407f-838b-38e4faecd21c
Content-Type: {{contentType}}


### Create Extract
# @name createExtract
POST http://{{host}}/extract
Content-Type: {{contentType}}

{
    "file": "/test.zip",
    "dir" : "/tmp/test"
}

### Create Background Extract
# @name createdBackgrounExtract
POST http://{{host}}/extract
Content-Type: {{contentType}}

{
    "file": "/test.zip",
    "dir" : "/tmp/test",
    "background": true
}

### Create Filtered Extract
# @name createFilteredExtract
POST http://{{host}}/extract
Content-Type: {{contentType}}

{
    "file": "/test.zip",
    "dir" : "/tmp/test",
    "filteredNames": "pull_request_builder"
}

### Create Background Filtered Extract
# @name createFBackgroundilteredExtract
POST http://{{host}}/extract
Content-Type: {{contentType}}

{
    "file": "/test.zip",
    "dir" : "/tmp/test",
    "background": true,
    "filteredNames": "pull_request_builder"
}

### Create Partial Extract
# @name createPartialExtract
POST http://{{host}}/extract
Content-Type: {{contentType}}

{
    "file": "/test.zip",
    "dir" : "/tmp/test",
    "PartialExtraction": "1|3|5"
}