@host = localhost:5001
@contentType = application/json

### Get Status
# @name getStatus
GET http://{{host}}/extract?id=c1f35e45-8148-407f-838b-38e4faecd21c
Content-Type: {{contentType}}


### Create Extract
# @name createExtract
POST http://{{host}}/extract
Content-Type: {{contentType}}

{
    "file": "/test.zip",
    "dir" : "/tmp/test",
    "background": true
}